# Sets env vars required for `dotnet` NuGet restore on this machine.
$env:Path = "C:\Program Files\dotnet;$env:Path"
$env:ProgramData = "C:\ProgramData"
$env:ProgramFiles = "C:\Program Files"
${env:ProgramFiles(x86)} = "C:\Program Files (x86)"
$env:SystemDrive = "C:"
$env:SystemRoot = "C:\Windows"
$env:windir = "C:\Windows"
$env:USERPROFILE = "C:\Users\Trrr"
$env:HOME = "C:\Users\Trrr"
$env:HOMEDRIVE = "C:"
$env:HOMEPATH = "\Users\Trrr"
$env:APPDATA = "C:\Users\Trrr\AppData\Roaming"
$env:LOCALAPPDATA = "C:\Users\Trrr\AppData\Local"
$env:TEMP = "C:\Users\Trrr\AppData\Local\Temp"
$env:TMP = "C:\Users\Trrr\AppData\Local\Temp"
$env:NUGET_PACKAGES = "C:\Users\Trrr\.nuget\packages"
